### ISSUE TITLE
Regarding 08-Functions and Methods Homework

### ISSUE THREAD

**Issue by Botir-01** [Pulatov-Javlon/Homework#4]
Write a function that checks whether a number is in a given range (inclusive of high and low)
Second option: 
def ran_check(num,low,high):
    if num in range(low,high+1):
        print('{} is in the range between {} and {}'.format(num,low,high))
    else:
        print('The number is outside the range.')

**Comment by Botir-01** [comment]
You have not done "Write a Python function to multiply all the numbers in a list." yet, Please solve it!

**Comment by Botir-01** [comment]
Please try to do 
Hard:
Write a Python function to check whether a string is pangram or not. (Assume the string passed in does not have any punctuation)

**Comment by Pulatov-Javlon** [comment]
Done!

**Comment by nguyen-hang** [comment]
import string

def ispangram(str1, alphabet=string.ascii_lowercase):
    str2 = ''
    for letter in str1:
        if letter.isalpha() == True:
            str2 = str2 + letter
        else: continue
    str2 = str2.lower()
    str2 = set(str2) #we can convert strings, list to set by this method
    alp = set(alphabet)
    return alp == str2
